export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS migrations (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci`,
  `CREATE TABLE IF NOT EXISTS projects (
    id CHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    path TEXT NOT NULL,
    default_branch VARCHAR(255) NOT NULL DEFAULT 'main',
    description TEXT NULL,
    latest_session_result TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci`,
  `CREATE TABLE IF NOT EXISTS worktrees (
    id CHAR(36) PRIMARY KEY,
    project_id CHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL,
    path TEXT NOT NULL,
    branch VARCHAR(255) NOT NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'clean',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_worktrees_project_name (project_id, name),
    CONSTRAINT fk_worktrees_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci`,
  `CREATE TABLE IF NOT EXISTS notes (
    id CHAR(36) PRIMARY KEY,
    project_id CHAR(36) NULL,
    title VARCHAR(255) NOT NULL,
    content LONGTEXT NOT NULL,
    tags TEXT NOT NULL,
    source_chat_suggestion_json TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_notes_project_id (project_id),
    CONSTRAINT fk_notes_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci`,
  `CREATE TABLE IF NOT EXISTS todos (
    id CHAR(36) PRIMARY KEY,
    project_id CHAR(36) NULL,
    source_note_id CHAR(36) NULL,
    title VARCHAR(255) NOT NULL,
    description LONGTEXT NOT NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'pending',
    tags TEXT NOT NULL,
    latest_session_result TEXT NULL,
    source_chat_suggestion_json TEXT NULL,
    completed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_todos_project_id (project_id),
    KEY idx_todos_source_note_id (source_note_id),
    KEY idx_todos_completed_at (completed_at),
    CONSTRAINT fk_todos_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL,
    CONSTRAINT fk_todos_source_note FOREIGN KEY (source_note_id) REFERENCES notes(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci`,
  `CREATE TABLE IF NOT EXISTS skills (
    id CHAR(36) PRIMARY KEY,
    project_id CHAR(36) NULL,
    name VARCHAR(255) NOT NULL,
    scope VARCHAR(64) NOT NULL DEFAULT 'global',
    prompt LONGTEXT NOT NULL,
    script LONGTEXT NULL,
    parameters TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_skills_project_name (project_id, name),
    CONSTRAINT fk_skills_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci`,
  `CREATE TABLE IF NOT EXISTS prompt_drafts (
    id CHAR(36) PRIMARY KEY,
    project_id CHAR(36) NOT NULL,
    todo_id CHAR(36) NULL,
    worktree_id CHAR(36) NULL,
    requested_worktree_name VARCHAR(255) NULL,
    source VARCHAR(64) NOT NULL DEFAULT 'direct',
    title VARCHAR(255) NOT NULL,
    prompt LONGTEXT NOT NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'draft',
    source_chat_suggestion_json TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_prompt_drafts_project_id (project_id),
    KEY idx_prompt_drafts_todo_id (todo_id),
    KEY idx_prompt_drafts_worktree_id (worktree_id),
    CONSTRAINT fk_prompt_drafts_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_prompt_drafts_todo FOREIGN KEY (todo_id) REFERENCES todos(id) ON DELETE SET NULL,
    CONSTRAINT fk_prompt_drafts_worktree FOREIGN KEY (worktree_id) REFERENCES worktrees(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci`,
  `CREATE TABLE IF NOT EXISTS sessions (
    id CHAR(36) PRIMARY KEY,
    project_id CHAR(36) NOT NULL,
    provider VARCHAR(64) NOT NULL DEFAULT 'claude',
    provider_thread_id VARCHAR(255) NULL,
    provider_metadata_json LONGTEXT NULL,
    worktree_id CHAR(36) NULL,
    todo_id CHAR(36) NULL,
    prompt_draft_id CHAR(36) NULL,
    requested_worktree_name VARCHAR(255) NULL,
    source VARCHAR(64) NOT NULL DEFAULT 'direct',
    name VARCHAR(255) NOT NULL DEFAULT '未命名会话',
    prompt LONGTEXT NOT NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'draft',
    runtime_status VARCHAR(64) NULL,
    summary LONGTEXT NULL,
    pid BIGINT NULL,
    cwd TEXT NULL,
    resolved_worktree_path TEXT NULL,
    exit_code INT NULL,
    last_activity_at DATETIME NULL,
    terminal_buffer LONGTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_sessions_project_id (project_id),
    KEY idx_sessions_worktree_id (worktree_id),
    KEY idx_sessions_todo_id (todo_id),
    KEY idx_sessions_prompt_draft_id (prompt_draft_id),
    CONSTRAINT fk_sessions_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_sessions_worktree FOREIGN KEY (worktree_id) REFERENCES worktrees(id) ON DELETE SET NULL,
    CONSTRAINT fk_sessions_todo FOREIGN KEY (todo_id) REFERENCES todos(id) ON DELETE SET NULL,
    CONSTRAINT fk_sessions_prompt_draft FOREIGN KEY (prompt_draft_id) REFERENCES prompt_drafts(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci`,
  `CREATE TABLE IF NOT EXISTS chat_sessions (
    id CHAR(36) PRIMARY KEY,
    project_id CHAR(36) NULL,
    worktree_id CHAR(36) NULL,
    title VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_chat_sessions_project_id (project_id),
    KEY idx_chat_sessions_worktree_id (worktree_id),
    CONSTRAINT fk_chat_sessions_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL,
    CONSTRAINT fk_chat_sessions_worktree FOREIGN KEY (worktree_id) REFERENCES worktrees(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci`,
  `CREATE TABLE IF NOT EXISTS chat_messages (
    sequence BIGINT NOT NULL AUTO_INCREMENT,
    id CHAR(36) NOT NULL,
    chat_session_id CHAR(36) NOT NULL,
    role VARCHAR(32) NOT NULL,
    content LONGTEXT NOT NULL,
    attachments_json LONGTEXT NOT NULL,
    artifact_suggestions_json LONGTEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tool_calls_json LONGTEXT NOT NULL,
    tool_results_json LONGTEXT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_chat_messages_sequence (sequence),
    KEY idx_chat_messages_session_sequence (chat_session_id, sequence),
    CONSTRAINT fk_chat_messages_session FOREIGN KEY (chat_session_id) REFERENCES chat_sessions(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci`
] as const;
